baseurl: "/"
title: "Stackbit Starter Theme"
init_is: "assets/js/init.js"
page_load_js: "assets/js/page-load.js"
page_unload_js: "assets/js/page-unload.js"
params:
  description: An ultra customizable generic theme for Stackbit
  header:
    title: Starter
    has_nav: true
    nav_links:
      - label: Features
        url: /features
        style: link
      - label: Blog
        url: /blog
        style: link
      - label: About
        url: /about
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Contact Us
        url: /contact
        style: primary
  footer:
    has_nav: true
    nav_links:
      - label: Contact Us
        url: /contact
        style: link
      - label: Privacy and Terms
        url: /terms
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        style: link
        new_window: true
      - label: GitHub
        url: https://github.com/
        style: link
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        style: link
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with <a href="https://www.stackbit.com" target="_blank" rel="noopener">Stackbit</a>.
sass:
  input_file: sass/main.scss
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: compressed
  precision: 10
